services:
  - type: web
    name: patient-portal
    env: node
    buildCommand: ./build-for-render.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: UPLOAD_DIR
        value: /opt/render/project/src/uploads
    healthCheckPath: /api/records
    autoDeploy: true 