services:
  - type: web
    name: patient-portal
    env: node
    buildCommand: |
      npm install
      cd client && npm install
      cd client && npm run build
      cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/records
    autoDeploy: true 