services:
  - type: web
    name: patient-portal
    env: node
    buildCommand: |
      echo "=== FORCING NPM BUILD PROCESS ==="
      echo "Current directory: $(pwd)"
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      echo "Installing backend dependencies..."
      npm install --no-package-lock
      echo "Installing frontend dependencies..."
      cd client
      npm install --no-package-lock
      echo "Building React app..."
      npm run build
      echo "Build verification..."
      ls -la build/
      echo "index.html exists: $(test -f build/index.html && echo 'YES' || echo 'NO')"
      cd ..
      echo "=== BUILD COMPLETE ==="
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/records
    autoDeploy: true 