services:
  - type: web
    name: patient-portal
    env: node
    buildCommand: |
      echo "Starting custom build process..."
      npm install
      echo "Backend dependencies installed"
      cd client
      echo "Installing client dependencies..."
      npm install
      echo "Building React app..."
      npm run build
      echo "Build completed"
      cd ..
      echo "Build process finished"
      ls -la client/build/
      echo "Running build verification..."
      node verify-build.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/records
    autoDeploy: true 